name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # todos los d√≠as a medianoche UTC
  workflow_dispatch:       # para correrlo manual cuando quieras
  push:
    branches:
      - main               # si tu rama principal es master, cambia main por master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: brjulioims
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
